import type { AutomationWorkflow } from '@/lib/automation-types'

const SOURCE =
  'Curated template from [n8n-free-templates](https://github.com/wassupjay/n8n-free-templates). Import JSON in n8n (⋮ → Import from File), connect credentials for each node, then Activate.'

function n8nTemplate(
  entry: Omit<AutomationWorkflow, 'platform' | 'jsonPath'> & {
    slug: string
    stack: string
    category: string
  },
): AutomationWorkflow {
  const { slug, stack, category, ...rest } = entry
  return {
    ...rest,
    platform: 'n8n',
    jsonPath: `/automations/n8n/${slug}.json`,
    detail: `${rest.detail ?? rest.description} Category: ${category}. Stack: ${stack}. ${SOURCE}`,
  }
}

/** 30 community n8n workflows (wassupjay/n8n-free-templates) */
export const N8N_COMMUNITY_WORKFLOWS: AutomationWorkflow[] = [
  n8nTemplate({
    id: 'n8n-resume-screening',
    slug: 'resume-screening',
    title: 'Resume Screening',
    description: 'Webhook intake, chunking, and LLM scoring for résumé pipelines.',
    category: 'AI & ML',
    stack: 'Cohere Embeddings · OpenAI Chat',
    tags: ['ai', 'hr', 'recruitment'],
    relatedHref: '/projects/prism',
    relatedLabel: 'See Prism project',
  }),
  n8nTemplate({
    id: 'n8n-customer-sentiment',
    slug: 'customer-sentiment-analysis',
    title: 'Customer Sentiment Analysis',
    description: 'Classify feedback sentiment and route alerts by score.',
    category: 'AI & ML',
    stack: 'Anthropic Claude · Cohere Embeddings · Pinecone',
    tags: ['ai', 'sentiment', 'pinecone'],
  }),
  n8nTemplate({
    id: 'n8n-summarize-emails',
    slug: 'summarize-customer-emails',
    title: 'Summarize Customer Emails',
    description: 'Ingest support emails and produce concise agent-ready summaries.',
    category: 'AI & ML',
    stack: 'Anthropic Claude · Cohere Embeddings',
    tags: ['ai', 'email', 'support'],
  }),
  n8nTemplate({
    id: 'n8n-product-descriptions',
    slug: 'product-description-generator',
    title: 'Product Description Generator',
    description: 'Generate on-brand product copy from catalog attributes.',
    category: 'AI & ML',
    stack: 'Anthropic Claude · Cohere Embeddings · Pinecone',
    tags: ['ai', 'ecommerce', 'copy'],
  }),
  n8nTemplate({
    id: 'n8n-daily-content-ideas',
    slug: 'daily-content-ideas',
    title: 'Daily Content Ideas',
    description: 'RAG-backed daily content ideas from your knowledge base.',
    category: 'AI & ML',
    stack: 'Cohere Embeddings · OpenAI Chat · Supabase Vector',
    tags: ['ai', 'content', 'rag'],
  }),
  n8nTemplate({
    id: 'n8n-auto-tag-blog',
    slug: 'auto-tag-blog-posts',
    title: 'Auto-tag Blog Posts',
    description: 'Auto-tag published posts for SEO and internal search.',
    category: 'AI & ML',
    stack: 'Anthropic Claude · OpenAI Embeddings · Supabase Vector',
    tags: ['ai', 'blog', 'seo'],
  }),
  n8nTemplate({
    id: 'n8n-ticket-urgency',
    slug: 'ticket-urgency-classification',
    title: 'Ticket Urgency Classification',
    description: 'Triage support tickets by urgency with vector context.',
    category: 'AI & ML',
    stack: 'Anthropic Claude · Cohere Embeddings · Pinecone',
    tags: ['ai', 'support', 'classification'],
  }),
  n8nTemplate({
    id: 'n8n-voice-transcription',
    slug: 'voice-note-transcription',
    title: 'Voice Note Transcription',
    description: 'Transcribe voice notes and structure output for downstream nodes.',
    category: 'AI & ML',
    stack: 'Cohere Embeddings · OpenAI Chat',
    tags: ['ai', 'transcription', 'voice'],
  }),
  n8nTemplate({
    id: 'n8n-lead-hubspot',
    slug: 'lead-to-hubspot',
    title: 'Lead to HubSpot',
    description: 'Parse inbound leads from email and sync to HubSpot.',
    category: 'Email',
    stack: 'Anthropic Claude · Cohere Embeddings · Supabase Vector',
    tags: ['email', 'crm', 'hubspot'],
  }),
  n8nTemplate({
    id: 'n8n-parse-invoices',
    slug: 'parse-invoice-emails',
    title: 'Parse Invoice Emails',
    description: 'Extract line items and totals from invoice attachments.',
    category: 'Email',
    stack: 'Anthropic Claude · OpenAI Embeddings',
    tags: ['email', 'finance', 'parser'],
  }),
  n8nTemplate({
    id: 'n8n-daily-digest',
    slug: 'daily-email-digest',
    title: 'Daily Email Digest',
    description: 'Morning digest of priority threads with AI summaries.',
    category: 'Email',
    stack: 'Anthropic Claude · OpenAI Embeddings · Supabase Vector',
    tags: ['email', 'digest', 'productivity'],
  }),
  n8nTemplate({
    id: 'n8n-follow-up-emails',
    slug: 'follow-up-emails',
    title: 'Follow-up Emails',
    description: 'Schedule and personalize follow-up sequences from CRM triggers.',
    category: 'Email',
    stack: 'Anthropic Claude · OpenAI Embeddings',
    tags: ['email', 'sales', 'sequences'],
  }),
  n8nTemplate({
    id: 'n8n-cross-post-blogs',
    slug: 'auto-post-blogs-linkedin-twitter',
    title: 'Auto-post Blogs to LinkedIn & X',
    description: 'Cross-post new blog URLs with AI-written captions.',
    category: 'Social',
    stack: 'Anthropic Claude · OpenAI Embeddings · Supabase Vector',
    tags: ['social', 'linkedin', 'twitter'],
  }),
  n8nTemplate({
    id: 'n8n-instagram-airtable',
    slug: 'schedule-instagram-from-airtable',
    title: 'Schedule Instagram from Airtable',
    description: 'Pull approved Airtable rows and queue Instagram posts.',
    category: 'Social',
    stack: 'Anthropic Claude · OpenAI Embeddings · Pinecone',
    tags: ['social', 'instagram', 'airtable'],
  }),
  n8nTemplate({
    id: 'n8n-youtube-comments',
    slug: 'youtube-comment-summarizer',
    title: 'YouTube Comment Summarizer',
    description: 'Summarize comment threads into creator briefs.',
    category: 'Social',
    stack: 'OpenAI Chat · OpenAI Embeddings · Pinecone',
    tags: ['social', 'youtube', 'ai'],
  }),
  n8nTemplate({
    id: 'n8n-social-report',
    slug: 'monthly-social-media-report',
    title: 'Monthly Social Media Report',
    description: 'Aggregate channel metrics into a monthly narrative report.',
    category: 'Social',
    stack: 'Anthropic Claude · OpenAI Embeddings',
    tags: ['social', 'analytics', 'report'],
  }),
  n8nTemplate({
    id: 'n8n-job-application-parser',
    slug: 'new-job-application-parser',
    title: 'New Job Application Parser',
    description: 'Parse applications into structured candidate records for ATS sync.',
    category: 'HR',
    stack: 'OpenAI Chat · OpenAI Embeddings · Pinecone',
    tags: ['hr', 'recruitment', 'parser'],
    relatedHref: '/projects/prism',
    relatedLabel: 'See Prism project',
  }),
  n8nTemplate({
    id: 'n8n-notion-job-board',
    slug: 'notion-job-board-poster',
    title: 'Notion Job Board Poster',
    description: 'Publish open roles from Notion to external job boards.',
    category: 'HR',
    stack: 'OpenAI Chat · OpenAI Embeddings · Supabase Vector',
    tags: ['hr', 'notion', 'jobs'],
  }),
  n8nTemplate({
    id: 'n8n-abandoned-cart',
    slug: 'abandoned-cart-email',
    title: 'Abandoned Cart Email',
    description: 'Recovery emails when carts idle past a threshold.',
    category: 'E-commerce',
    stack: 'Cohere Embeddings · OpenAI Chat · Supabase Vector',
    tags: ['ecommerce', 'email', 'cart'],
  }),
  n8nTemplate({
    id: 'n8n-shopify-sms',
    slug: 'shopify-order-sms',
    title: 'Shopify Order SMS',
    description: 'SMS confirmations and updates on new Shopify orders.',
    category: 'E-commerce',
    stack: 'Anthropic Claude · Cohere Embeddings · Pinecone',
    tags: ['ecommerce', 'shopify', 'sms'],
  }),
  n8nTemplate({
    id: 'n8n-inventory-slack',
    slug: 'inventory-slack-alert',
    title: 'Inventory Slack Alert',
    description: 'Low-stock SKUs to Slack with reorder suggestions.',
    category: 'E-commerce',
    stack: 'Cohere Embeddings · OpenAI Chat · Pinecone',
    tags: ['ecommerce', 'inventory', 'slack'],
  }),
  n8nTemplate({
    id: 'n8n-stripe-quickbooks',
    slug: 'stripe-to-quickbooks',
    title: 'Stripe to QuickBooks',
    description: 'Map Stripe charges to QuickBooks with validation steps.',
    category: 'Finance',
    stack: 'OpenAI Chat · OpenAI Embeddings · Supabase Vector',
    tags: ['finance', 'stripe', 'quickbooks'],
  }),
  n8nTemplate({
    id: 'n8n-unpaid-invoice',
    slug: 'unpaid-invoice-reminder',
    title: 'Unpaid Invoice Reminder',
    description: 'Escalating reminder emails for overdue invoices.',
    category: 'Finance',
    stack: 'Cohere Embeddings · OpenAI Chat',
    tags: ['finance', 'invoices', 'email'],
  }),
  n8nTemplate({
    id: 'n8n-ocr-receipts',
    slug: 'ocr-receipts-to-notion',
    title: 'OCR Receipts to Notion',
    description: 'OCR receipt images into Notion expense rows.',
    category: 'Finance',
    stack: 'Anthropic Claude · OpenAI Embeddings · Supabase Vector',
    tags: ['finance', 'ocr', 'notion'],
  }),
  n8nTemplate({
    id: 'n8n-github-jenkins',
    slug: 'github-commit-jenkins',
    title: 'GitHub Commit → Jenkins',
    description: 'Trigger Jenkins builds and notify on GitHub push events.',
    category: 'DevOps',
    stack: 'OpenAI Chat · OpenAI Embeddings · Supabase Vector',
    tags: ['devops', 'github', 'ci'],
  }),
  n8nTemplate({
    id: 'n8n-appointment-whatsapp',
    slug: 'appointment-whatsapp-notify',
    title: 'Appointment WhatsApp Notify',
    description: 'WhatsApp reminders for upcoming patient appointments.',
    category: 'Healthcare',
    stack: 'OpenAI Chat · OpenAI Embeddings · Supabase Vector',
    tags: ['healthcare', 'whatsapp', 'scheduling'],
  }),
  n8nTemplate({
    id: 'n8n-youtube-to-blog',
    slug: 'youtube-transcript-to-blog',
    title: 'YouTube Transcript to Blog',
    description: 'Turn YouTube transcripts into draft blog posts with headings.',
    category: 'Creative',
    stack: 'Anthropic Claude · OpenAI Embeddings · Pinecone',
    tags: ['creative', 'youtube', 'blog'],
  }),
  n8nTemplate({
    id: 'n8n-morning-briefing',
    slug: 'morning-briefing-email',
    title: 'Morning Briefing Email',
    description: 'Morning briefing: calendar, tasks, and news in one email.',
    category: 'Productivity',
    stack: 'Anthropic Claude · Cohere Embeddings · Supabase Vector',
    tags: ['productivity', 'email', 'briefing'],
  }),
  n8nTemplate({
    id: 'n8n-api-monitor',
    slug: 'api-monitor-auto-restart',
    title: 'API Monitor Auto Restart',
    description: 'Health-check APIs and restart or alert on failure.',
    category: 'Ops',
    stack: 'OpenAI Chat · OpenAI Embeddings',
    tags: ['ops', 'monitoring', 'api'],
  }),
  n8nTemplate({
    id: 'n8n-voice-notion',
    slug: 'voice-task-to-notion',
    title: 'Voice Task to Notion',
    description: 'Voice memo → transcribed task card in Notion.',
    category: 'Ops',
    stack: 'OpenAI Chat · OpenAI Embeddings',
    tags: ['ops', 'notion', 'voice'],
  }),
]
