import type { ProjectTechnicalSpec } from '@/lib/project-technical'
import {
  UNIFY_ARCHITECTURE_LAYERS,
  UNIFY_FLOW_STEPS,
  UNIFY_STACK_GROUPS,
  UNIFY_TECH_STATS,
} from '@/lib/unify-tech'

type SpecOverrides = Partial<ProjectTechnicalSpec>

export const PROJECT_TECHNICAL_SPECS: Record<string, SpecOverrides> = {
  socialhub: {
    summary:
      'Production GenOps platform: Next.js dashboard, FastAPI service mesh, multi-LLM AI orchestrator, async worker pool, and OAuth publishers across five social networks — all on a PostgreSQL + Redis + S3 + pgvector data plane.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CLIENT      Next.js dashboard · Studio · Calendar · UGC editor   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │  HTTPS · JWT · OAuth flows',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ EDGE        Next.js SSR · rate limit · OAuth callbacks · CDN     │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │',
      '┌────────────────────────────────▼─────────────────────────────────┐',
      '│ APPLICATION   FastAPI service mesh                               │',
      '│   Content-gen │ Assets │ Schedule │ Approvals │ Analytics │ Auth │',
      '└──┬───────────┬─────────┬──────────┬──────────────┬───────────────┘',
      '   │           │         │          │              │',
      '   ▼           ▼         ▼          ▼              ▼',
      '┌──────┐  ┌─────────┐  ┌──────────┐  ┌──────────┐  ┌─────────┐',
      '│ LLM  │  │ Image   │  │ Brand    │  │ Telegram │  │ Worker  │',
      '│GPT-4o│  │ DALL·E  │  │ RAG      │  │ approval │  │ pool    │',
      '│Claude│  │ Fal.ai  │  │ pgvector │  │ bot      │  │ (Celery)│',
      '└──────┘  └─────────┘  └──────────┘  └──────────┘  └────┬────┘',
      '                                                        │  schedule + retry',
      '┌───────────────────────────────────────────────────────▼──────────┐',
      '│ DATA        PostgreSQL · Redis · S3 (12M assets) · pgvector      │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ OAuth tokens per platform',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CHANNELS    Facebook · Instagram · X · LinkedIn · Reddit         │',
      '│             Direct publish — image + caption · no passwords      │',
      '└──────────────────────────────────────────────────────────────────┘',
      '',
      'OBS  Langfuse traces · Sentry · Prometheus + Grafana · audit log',
    ].join('\n'),
    layers: [
      {
        title: 'Client',
        detail:
          'Next.js dashboard surfaces — AI Content Studio, smart calendar, UGC editor, document intelligence, analytics. Single-tenant per workspace with role-based UI.',
      },
      {
        title: 'Edge / auth',
        detail:
          'Next.js SSR with JWT sessions, per-route rate limits, and OAuth callback handlers for each social network. CDN-served static assets.',
      },
      {
        title: 'Application services',
        detail:
          'FastAPI service mesh — content generation, asset library, scheduling, approval routing, analytics aggregation, and an auth/OAuth token service that refreshes platform credentials.',
      },
      {
        title: 'AI orchestrator',
        detail:
          'LLM router (GPT-4o, Claude) for copy and prompts; image generators (DALL·E 3, Fal.ai); RAG retrieval over brand docs stored in pgvector; Langfuse traces every call.',
      },
      {
        title: 'Worker plane',
        detail:
          'Celery + Redis queue: scheduled posts, retries with exponential backoff, async image generation, OAuth token refresh, and webhook fan-out to channel publishers.',
      },
      {
        title: 'Data plane',
        detail:
          'PostgreSQL for content/schedules/users; Redis for cache and queue; S3 (or compatible) for 12M+ assets; pgvector for brand document embeddings.',
      },
      {
        title: 'Channels',
        detail:
          'Per-platform OAuth publishers (Facebook, Instagram, X, LinkedIn, Reddit) — push captions + media; no passwords ever stored.',
      },
    ],
    technologies: [
      {
        group: 'Application',
        items: ['FastAPI', 'Next.js', 'TypeScript', 'Python', 'Celery'],
      },
      {
        group: 'AI',
        items: ['GPT-4o', 'Claude', 'DALL·E 3', 'Fal.ai', 'RAG', 'pgvector'],
      },
      {
        group: 'Data',
        items: ['PostgreSQL', 'Redis', 'S3', 'pgvector', 'OAuth 2.0'],
      },
      {
        group: 'Ops',
        items: ['Docker', 'Langfuse', 'Sentry', 'Prometheus', 'Grafana'],
      },
    ],
    inputs: [
      {
        label: 'Brand context',
        format: 'PDF / docs / URLs',
        description: 'Ingested into pgvector with embeddings for RAG retrieval at generation time.',
      },
      {
        label: 'Campaign brief',
        format: 'JSON (topic, tone, platforms, window)',
        description: 'Drives the AI orchestrator and scheduler.',
      },
      {
        label: 'OAuth grants',
        format: 'Platform OAuth tokens',
        description: 'Per-platform credentials with refresh + scope minimization.',
      },
    ],
    outputs: [
      {
        label: 'Scheduled posts',
        format: 'Per-channel publish jobs',
        description: 'Caption + media payloads queued for the OAuth publishers.',
      },
      {
        label: 'Asset library',
        format: 'S3 + DB metadata',
        description: 'Centralized inventory of generated and uploaded media.',
      },
      {
        label: 'Analytics',
        format: 'Aggregated metrics API',
        description: 'Engagement, reach, and asset usage across connected accounts.',
      },
    ],
    results: [
      { label: 'Posts generated', value: '500K+', detail: 'Production throughput' },
      { label: 'Assets managed', value: '12M+', detail: 'Centralized media library' },
      { label: 'Channels', value: '5', detail: 'FB · IG · X · LI · Reddit' },
      { label: 'Auth model', value: 'OAuth only', detail: 'Zero stored passwords' },
    ],
  },

  prism: {
    summary:
      'Custom recruitment AI: FastAPI service + Celery workers ingest applications from Gmail, parse documents, extract structured candidate data with GPT-4 under strict JSON schemas, run a weighted scoring engine, and schedule interviews through the Google Calendar API.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SOURCES     Gmail (job inbox) · Careers form · Manual upload     │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ Gmail API push · webhook',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ INGEST      Email service · attachment fetch · dedup             │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │',
      '┌────────────────────────────────▼─────────────────────────────────┐',
      '│ APPLICATION  (FastAPI + Celery on Redis)                         │',
      '│   Parser  →  Extraction  →  Scoring  →  Pipeline  →  Scheduler   │',
      '└────┬──────────────┬─────────────┬───────────┬─────────┬──────────┘',
      '     │              │             │           │         │',
      '     ▼              ▼             ▼           ▼         ▼',
      '┌─────────┐  ┌──────────────┐  ┌────────┐  ┌──────┐  ┌──────────┐',
      '│ PDF /   │  │ GPT-4 JSON   │  │ Score  │  │ State│  │ GCal     │',
      '│ DOCX    │  │ schema       │  │ engine │  │ FSM  │  │ invite   │',
      '│ extract │  │ validator    │  │ (rules)│  │      │  │ + email  │',
      '└─────────┘  └──────────────┘  └────────┘  └──────┘  └──────────┘',
      '',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DATA        PostgreSQL (candidates · roles · scores) · Redis     │',
      '│             Object store (raw résumés) · audit log               │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DASHBOARD   Next.js · recruiter inbox · scoring view · overrides │',
      '└──────────────────────────────────────────────────────────────────┘',
      '',
      'OBS  Structured logs · per-candidate trace · SLA timers',
    ].join('\n'),
    layers: [
      {
        title: 'Sources',
        detail:
          'Gmail job inbox (Gmail API push notifications), careers form webhooks, and manual recruiter upload — all normalized into application events.',
      },
      {
        title: 'Ingest',
        detail:
          'Email worker fetches attachments, deduplicates by message-id, and persists raw artifacts to object storage before parsing.',
      },
      {
        title: 'Application services (FastAPI + Celery)',
        detail:
          'Parser (PDF/DOCX/text), GPT-4 extraction with strict JSON-schema validation and retry, weighted scoring engine, candidate state machine, and Google Calendar scheduling service.',
      },
      {
        title: 'Data plane',
        detail:
          'PostgreSQL for candidates, roles, scores, and pipeline state; Redis for Celery + caching; object storage for raw résumé files; immutable audit log.',
      },
      {
        title: 'Recruiter dashboard',
        detail:
          'Next.js app — inbox, ranked candidate view, score explainability, manual override, and interview-slot booking. Talks to FastAPI over JWT-protected APIs.',
      },
      {
        title: 'External integrations',
        detail:
          'Gmail API (inbound + replies), Google Calendar API (invites), and configurable webhooks for ATS systems.',
      },
    ],
    technologies: [
      {
        group: 'Backend',
        items: ['FastAPI', 'Python', 'Celery', 'Redis', 'PostgreSQL'],
      },
      {
        group: 'AI',
        items: ['OpenAI GPT-4', 'JSON Schema', 'Pydantic validation'],
      },
      {
        group: 'Integrations',
        items: ['Gmail API', 'Google Calendar API', 'Webhooks', 'OAuth 2.0'],
      },
      {
        group: 'Frontend / ops',
        items: ['Next.js', 'TypeScript', 'Docker', 'Structured logging'],
      },
    ],
    inputs: [
      { label: 'Inbound résumé', format: 'Email + PDF/DOCX', description: 'Gmail-triggered application with attachments.' },
      { label: 'Job criteria', format: 'JSON role config', description: 'Skills, seniority, must-haves, and scoring weights.' },
    ],
    outputs: [
      { label: 'Ranked candidate', format: 'PostgreSQL row', description: 'Structured fields, score, and explainability factors.' },
      { label: 'Interview invite', format: 'GCal event + email', description: 'Auto-booked slots for candidates above threshold.' },
    ],
    results: [
      { label: 'Manual screening', value: '80–85%↓', detail: 'Recruiter time removed' },
      { label: 'Per candidate', value: '15–30 min saved', detail: 'Default automated path' },
      { label: 'Extraction', value: 'JSON-schema', detail: 'GPT-4 with retry-on-fail' },
    ],
  },

  dbaas: {
    summary:
      'DBaaS Social Hub (Content Phase / dbasssocialhub): React 19 + Vite 7 SPA, FastAPI backend on Apex SaaS with Alembic migrations, modular services for AI content, content calendar, persona agents, UGC, OAuth credentials, and scheduled multi-platform publishing — PostgreSQL + Cloudinary + Docker Compose, documented in SYSTEM_ARCHITECTURE.md.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CLIENT      React 19 + Vite 7 · Tailwind 4 · Framer · Three.js   │',
      '│             Landing · Generator · Calendar · UGC · Agents        │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ HTTPS · JWT (Apex auth)',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ APEX + API    FastAPI · Apex bootstrap · slowapi rate limits     │',
      '└──┬─────────┬──────────┬─────────┬──────────┬───────────────────┘',
      '   │         │          │         │          │',
      '   ▼         ▼          ▼         ▼          ▼',
      '┌──────┐ ┌─────────┐ ┌───────┐ ┌─────┐ ┌────────────────────────┐',
      '│ AI   │ │Calendar │ │Agents │ │ UGC │ │ OAuth + platform       │',
      '│content│ │ planner │ │Flux IP│ │edit │ │ FB · IG · X · LI · RD  │',
      '└──┬───┘ └────┬────┘ └───┬───┘ └──┬──┘ └───────────┬────────────┘',
      '   │          │          │        │                │',
      '   └──────────┴──────────┴────────┴────────────────┘',
      '                                 │',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ WORKER      APScheduler · scheduler_worker (60s poll · publish)  │',
      '│ TELEGRAM    Bot service — same FastAPI service layer as web      │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │',
      '┌────────────────────────────────▼─────────────────────────────────┐',
      '│ DATA        PostgreSQL 15 · Cloudinary · Fernet OAuth tokens     │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ AI PROVIDERS   OpenAI GPT-4o / DALL·E 3 · Fal.ai · Gemini (UGC) │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    layers: [
      {
        title: 'Client (Vite SPA)',
        detail:
          'React 19 pages: Liquid Ether landing, post generator, Content Calendar super-controller, UGC editor, persona Agents, OAuth connections, scheduler, payments. Axios to FastAPI with auth context.',
      },
      {
        title: 'API + Apex SaaS',
        detail:
          'FastAPI with apex.bootstrap, SQLAlchemy models, Alembic migrations. Routes: health, posts, scheduled, ai_content, enhance, credentials, ugc, content_calendar, agents, social_posting, scheduler.',
      },
      {
        title: 'AI & media pipeline',
        detail:
          'GPT-4o for platform copy and prompt enhancement; DALL·E 3 and Fal.ai (Nano Banana, Flux Pro/Dev) for images; agent_service for IP-Adapter personas; pdf_extraction_service for brand PDFs; ugc_service (Gemini) for edits.',
      },
      {
        title: 'Calendar & scheduling',
        detail:
          'Monthly plan generation from business profile; bulk asset generation; scheduled_posts table; background worker publishes to all selected platforms with per-platform status.',
      },
      {
        title: 'OAuth & channels',
        detail:
          'Encrypted credential store per platform profile. Publishers for Facebook, Instagram, Twitter (hybrid v1.1/v2 media), LinkedIn (non-PKCE), Reddit. No password storage.',
      },
      {
        title: 'Data & deploy',
        detail:
          'PostgreSQL 15 in Docker Compose; Cloudinary for media URLs; production CORS for socialhub.apexneural.cloud and ai-content.apexneural.cloud.',
      },
    ],
    technologies: [
      {
        group: 'Frontend',
        items: ['React 19', 'Vite 7', 'TypeScript', 'Tailwind CSS 4', 'Framer Motion', 'Three.js'],
      },
      {
        group: 'Backend',
        items: ['FastAPI', 'Apex SaaS', 'SQLAlchemy', 'Alembic', 'APScheduler', 'PostgreSQL 15', 'Docker Compose'],
      },
      {
        group: 'AI',
        items: ['OpenAI GPT-4o', 'DALL·E 3', 'Fal.ai', 'Gemini (UGC)', 'Flux IP-Adapter'],
      },
      {
        group: 'Integrations',
        items: ['Facebook Graph', 'Instagram', 'X API', 'LinkedIn', 'Reddit', 'Telegram Bot', 'Cloudinary'],
      },
    ],
    inputs: [
      { label: 'Business profile', format: 'Form + PDF', description: 'Brand voice, offerings, and visuals from PDF document intelligence.' },
      { label: 'OAuth tokens', format: 'Per-platform credentials', description: 'User-connected social accounts; Fernet-encrypted at rest.' },
      { label: 'Content brief', format: 'Text / calendar plan', description: 'Single post or monthly calendar slot with platform targets.' },
    ],
    outputs: [
      { label: 'Posts & assets', format: 'Copy + image URLs', description: 'Platform-specific captions and Cloudinary-hosted media.' },
      { label: 'Scheduled publishes', format: 'DB + API status', description: 'Due posts executed by worker; per-platform success/failure logged.' },
    ],
    results: [
      { label: 'Platforms', value: '5', detail: 'FB · IG · X · LinkedIn · Reddit' },
      { label: 'Deploy', value: 'Docker', detail: 'Postgres + API + SPA' },
      { label: 'Docs', value: 'In-repo', detail: 'SYSTEM_ARCHITECTURE.md' },
      { label: 'Source', value: 'Samsung SSD', detail: 'dbaas/social-hub/dbasssocialhub' },
    ],
  },

  'sugarcane-health-ml': {
    summary:
      'Comparative ML research pipeline on a faculty-curated sugarcane health dataset: parallel training of transfer-learning CNNs (VGG19, ResNet) and classical SVM baselines on the same train/eval splits, with documented metrics for a co-authored research report.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DATASET     Sugarcane field images · faculty labeling protocol  │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ stratified train / val / test',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ PREPROCESS  Resize · normalize · augmentation · class balancing │',
      '└──┬───────────────────────────────────────────────────┬──────────┘',
      '   │                                                   │',
      '   ▼ deep learning track                               ▼ classical track',
      '┌─────────────────────────────────┐         ┌─────────────────────┐',
      '│ Transfer learning               │         │ Feature engineering │',
      '│   VGG19 · ResNet (PyTorch/Keras)│         │   HOG · color hist  │',
      '│   fine-tune head + last blocks  │         │   SVM (scikit-learn)│',
      '└──────────────┬──────────────────┘         └──────────┬──────────┘',
      '               │                                       │',
      '               └────────────────┬──────────────────────┘',
      '                                ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ EVALUATION   Accuracy · precision · recall · confusion matrix    │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DELIVERABLE  Research report · checkpoints · reproducible splits │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'Crop images', format: 'JPEG/PNG dataset', description: 'Sugarcane health classes with stratified splits.' },
      { label: 'Labels', format: 'Class indices + metadata', description: 'Disease/stress annotations from faculty protocol.' },
    ],
    outputs: [
      { label: 'Model checkpoints', format: 'PyTorch/Keras weights', description: 'Best CNN and SVM artifacts per metric.' },
      { label: 'Research report', format: 'PDF', description: 'Methodology, confusion matrices, model trade-offs.' },
    ],
    results: [
      { label: 'Deep models', value: 'VGG19 · ResNet', detail: 'Transfer learning' },
      { label: 'Classical baseline', value: 'SVM + HOG', detail: 'Apples-to-apples eval' },
      { label: 'Output', value: 'Research doc', detail: 'Co-authored with faculty' },
    ],
  },

  unify: {
    summary:
      'Multi-tenant omni-channel L1 platform: NestJS monorepo (conversations, RBAC, BullMQ, channel webhooks) + FastAPI L1 agent (NLU, orchestrator, tool calls) on PostgreSQL with row-level security per tenant.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CHANNELS    WhatsApp · Telegram · Instagram · Email · Web chat   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ webhooks · tenant resolved',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ PLATFORM (NestJS 11 monorepo · kalamandir-l1)                    │',
      '│   API gateway · JWT auth · tenant middleware · RBAC (29 perms)   │',
      '│   Conversations · tickets · ownership locks · audit log          │',
      '└──┬──────────────────────────────────────────────────┬────────────┘',
      '   │                                                  │',
      '   │ BullMQ (queue)                                   │ REST call',
      '   ▼                                                  ▼',
      '┌──────────────────────┐                  ┌──────────────────────┐',
      '│ Outbound workers     │                  │ L1 AGENT (FastAPI)   │',
      '│ delivery · retries   │                  │ POST /api/v1/message │',
      '│ rate limit per chan  │                  │ 7-step pipeline      │',
      '└──────────────────────┘                  └──────────┬───────────┘',
      '                                                     │',
      '   ┌─────────────────────────────────────────────────┤',
      '   ▼               ▼                ▼                ▼',
      '┌────────┐  ┌──────────────┐  ┌──────────┐  ┌────────────────┐',
      '│Content │  │ Translate    │  │ Catalog  │  │ Orders /       │',
      '│guard   │  │ EN·HI·TE·HG  │  │ search   │  │ payments tools │',
      '│        │  │              │  │pgvector  │  │                │',
      '└────────┘  └──────────────┘  └──────────┘  └────────────────┘',
      '',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DATA   PostgreSQL 16 + RLS (app.tenant_id) · Redis · pgvector    │',
      '│        Per-tenant credentials · audit log · ticket store         │',
      '└──────────────────────────────────────────────────────────────────┘',
      '',
      'INFRA  AWS ECS · RDS · ElastiCache (Terraform) · structlog · Sentry',
    ].join('\n'),
    layers: UNIFY_ARCHITECTURE_LAYERS.map((l) => ({
      title: l.title,
      detail: l.detail,
    })),
    flow: UNIFY_FLOW_STEPS.map((f) => ({
      step: f.step,
      title: f.title,
      body: f.body,
    })),
    technologies: UNIFY_STACK_GROUPS.map((g) => ({
      group: g.group,
      items: [...g.items],
    })),
    inputs: [
      {
        label: 'Inbound message',
        format: 'Channel webhook JSON',
        description: 'WhatsApp, Telegram, Instagram, or web chat — resolved to tenant + conversation.',
      },
      {
        label: 'Thread context',
        format: 'conversation_id + tenant_id',
        description: 'Full history loaded with RLS-pinned tenant scope.',
      },
    ],
    outputs: [
      {
        label: 'L1 reply',
        format: 'Channel-formatted text/media',
        description: 'Catalog search, orders, payments, or escalate-to-human signal.',
      },
      {
        label: 'Ticket / audit',
        format: 'PostgreSQL rows',
        description: 'Escalation, ownership locks, audit trail, supervisor view.',
      },
    ],
    results: UNIFY_TECH_STATS.map((s) => ({
      label: s.label,
      value: s.value,
      detail: s.sub,
    })),
  },

  taleweaver: {
    summary:
      'Three-tier book generation stack: React/Vite frontend, FastAPI orchestration with WebSocket streaming, and a GPU LLM service running Qwen2.5-3B + a Fitzgerald LoRA adapter — backed by an offline fine-tuning pipeline that turns ePubs into instruction data.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CLIENT      React + Vite (Bookgen UI) — outline · chapters · pub │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ HTTPS + WebSocket',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ BACKEND     FastAPI · session state · WS fan-out · export jobs   │',
      '└──┬───────────────────────────────┬──────────────────────────┬────┘',
      '   │ REST                          │ WS stream                │ jobs',
      '   ▼                               ▼                          ▼',
      '┌──────────────┐         ┌──────────────────────┐    ┌──────────────┐',
      '│ Outline      │         │ LLM-SERVICE (GPU)    │    │ EPUB / PDF   │',
      '│ generator    │         │ Qwen2.5-3B + LoRA    │    │ exporter     │',
      '│              │         │ token streaming      │    │ ebooklib     │',
      '└──────────────┘         └──────────┬───────────┘    └──────────────┘',
      '                                    │',
      '                       ┌────────────┴─────────────┐',
      '                       ▼                          ▼',
      '              ┌─────────────────┐        ┌──────────────────┐',
      '              │ Adapter weights │        │ Base model cache │',
      '              │ fitzgerald_lora │        │ (transformers)   │',
      '              └────────┬────────┘        └──────────────────┘',
      '                       │ trained offline',
      '┌──────────────────────▼──────────────────────────────────────────┐',
      '│ TRAINING PIPELINE (companion repo `finetune/`)                  │',
      '│   ePub → extract → segment → instruction-gen → dataset.jsonl    │',
      '│   → PEFT LoRA train on Qwen2.5-3B (3,762 examples)              │',
      '└─────────────────────────────────────────────────────────────────┘',
      '',
      'DATA  PostgreSQL (projects · chapters) · object store (exports)',
    ].join('\n'),
    layers: [
      { title: 'Frontend', detail: 'React/Vite Bookgen UI — outline editor, streaming chapter view, export controls.' },
      { title: 'Backend', detail: 'FastAPI orchestration, session and outline state, WebSocket fan-out per chapter, and export job dispatcher.' },
      { title: 'LLM service (GPU)', detail: 'Qwen2.5-3B base model + Fitzgerald PEFT LoRA adapter (~479 MB), streaming generation with sampling controls.' },
      { title: 'Training pipeline', detail: 'Offline `finetune/` repo turns ePub corpora into 3,762 instruction examples, then trains a LoRA adapter consumed by the LLM service.' },
      { title: 'Data + export', detail: 'PostgreSQL for projects, outlines, chapters; object storage for EPUB/PDF exports.' },
    ],
    inputs: [
      { label: 'Story premise', format: 'JSON outline', description: 'Genre, characters, chapter plan, tone.' },
      { label: 'Style adapter', format: 'LoRA weights', description: 'Fitzgerald voice trained from 5 ePub sources.' },
    ],
    outputs: [
      { label: 'Chapters', format: 'WebSocket token stream', description: 'Live streaming generation per chapter.' },
      { label: 'Manuscript', format: 'EPUB / PDF', description: 'Export-ready book files.' },
    ],
    results: [
      { label: 'Training examples', value: '3,762', detail: 'From 5 books' },
      { label: 'Deploy tiers', value: '3', detail: 'frontend · backend · llm-service' },
      { label: 'Adapter size', value: '~479 MB', detail: 'PEFT LoRA on Qwen2.5-3B' },
    ],
  },

  'linkedin-job-scraper': {
    summary:
      'Python data pipeline: rotating-session guest-API scraper feeds raw HTML postings into a Claude 3.5 structured-extraction stage, which writes ten typed fields per row into a formatted Excel workbook.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ INPUT       Search URLs · region filters · session env config    │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SCRAPER     linkedin_scraper.py · session pool · UA rotation     │',
      '│             random delay · MAX_JOBS_PER_SESSION cap              │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ HTML posts',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ PARSER      BeautifulSoup → normalized fields                    │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ AI EXTRACT  ai_extractor.py · OpenRouter Claude 3.5              │',
      '│             10-field JSON schema (company · role · skills · …)   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ WRITER      excel_writer.py · openpyxl · linkedin_ai_jobs.xlsx   │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'Job listings', format: 'LinkedIn guest HTML', description: 'AI/ML roles, USA & UAE — no login required.' },
      { label: 'Session config', format: 'ENV', description: 'MAX_JOBS_PER_SESSION, delays, UA rotation.' },
    ],
    outputs: [
      {
        label: 'Structured rows',
        format: 'linkedin_ai_jobs.xlsx',
        description: '10 fields per row: company, role, skills, salary, mode, full JD, etc.',
      },
    ],
    results: [
      { label: 'Fields per job', value: '10', detail: 'Claude-structured' },
      { label: 'Anti-ban', value: 'Delays + caps', detail: 'Session limits + UA rotation' },
    ],
  },

  'b2b-lead-platform': {
    summary:
      'FastAPI + PostgreSQL platform: pluggable signal collectors call 7+ external APIs in parallel, an async discovery scheduler enriches accounts, and a weighted scoring engine writes explainable lead scores to a database surfaced through Streamlit and FastAPI UIs.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SOURCES   Muse · News API · Guardian · Alpha Vantage · …         │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ async fan-out',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ COLLECTORS  Hiring · Funding · News · Growth · Contact (modular) │',
      '└──┬───────────┬────────────┬─────────────┬───────────┬────────────┘',
      '   │           │            │             │           │',
      '   └───────────┴────────────┴─────────────┴───────────┘',
      '                                 │ normalized signals',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SCORING ENGINE (weighted)                                        │',
      '│   Hiring 25% · Funding 25% · Competition 20% · Growth 20% · 10%  │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DATA        PostgreSQL · SQLAlchemy ORM · Alembic migrations     │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │',
      '                ┌────────────────┴────────────────┐',
      '                ▼                                 ▼',
      '         ┌──────────────┐                  ┌──────────────┐',
      '         │ FastAPI UI   │                  │ Streamlit    │',
      '         │ dashboard    │                  │ analyst view │',
      '         └──────────────┘                  └──────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'Company signals', format: 'REST API JSON', description: 'Hiring, funding, news, competition from 7+ APIs.' },
    ],
    outputs: [
      { label: 'Lead scores', format: 'DB rows + UI', description: 'Weighted score 0–100 with explainable factors.' },
    ],
    results: [
      { label: 'Hiring weight', value: '25%' },
      { label: 'Funding weight', value: '25%' },
      { label: 'Discovery', value: 'Async jobs', detail: 'Background enrichment' },
    ],
  },

  madhost: {
    summary:
      'Minimal short-term rental ops bot: FastAPI + SQLite, single-page maintenance UI, WhatsApp Business API for guest welcomes on check-in, and Telegram Bot API for cleaning tasks on checkout.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ UI          Single-page maintenance form (served by FastAPI)     │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ API         FastAPI · SQLAlchemy · SQLite                        │',
      '│   /booking · /checkout · /guests                                 │',
      '└──┬─────────────────────────────────────────────────────┬─────────┘',
      '   │ on booking                                          │ on checkout',
      '   ▼                                                     ▼',
      '┌────────────────────────┐                  ┌────────────────────────┐',
      '│ WhatsApp Business API  │                  │ Telegram Bot API       │',
      '│ guest welcome message  │                  │ cleaner task message   │',
      '└────────────────────────┘                  └────────────────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'Guest phone', format: 'E.164', description: 'Stored on booking create.' },
      { label: 'Checkout event', format: 'HTTP POST', description: 'Triggers cleaning workflow.' },
    ],
    outputs: [
      { label: 'Guest message', format: 'WhatsApp template', description: 'Automated welcome on check-in.' },
      { label: 'Cleaner task', format: 'Telegram message', description: 'Sent to CLEANER_TELEGRAM_CHAT_ID.' },
    ],
  },

  'ai-twitter-post-generator': {
    summary:
      'FastAPI service with a static approval UI: research workers scrape AI news, a Claude drafting stage produces persona-styled tweets, Fal Flux generates an image per draft, and approved items are published to X via Tweepy.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ FEEDS       HN · TechCrunch · MIT · OpenAI (RSS + scrape)        │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ RESEARCH    FastAPI worker · feedparser + BeautifulSoup          │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DRAFT       Anthropic Claude · persona.json voice constraints    │',
      '└────────┬────────────────────────────────────┬────────────────────┘',
      '         │                                    │',
      '         ▼                                    ▼',
      '┌────────────────────┐                ┌───────────────────────────┐',
      '│ Fal Flux image gen │                │ Approval UI (static HTML) │',
      '└─────────┬──────────┘                └──────────┬────────────────┘',
      '          │                                      │',
      '          └──────────────────┬───────────────────┘',
      '                             ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ PUBLISH     /api/twitter/post · Tweepy → X                       │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'News feeds', format: 'RSS / scrape', description: 'HN, TechCrunch, MIT, OpenAI sources.' },
      { label: 'Persona', format: 'persona.json', description: 'Voice and topic constraints.' },
    ],
    outputs: [
      { label: 'Draft tweet', format: 'Text + image URL', description: 'Pending human approval.' },
      { label: 'Published tweet', format: 'Twitter API', description: 'After approve endpoint.' },
    ],
  },

  'fitzgerald-lora-pipeline': {
    summary:
      'Offline ML pipeline: ePub corpora are extracted, segmented, turned into instruction examples, and used to PEFT-train a LoRA adapter on Qwen2.5-3B — the trained weights are then consumed by the Bookgen `llm-service`.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CORPUS      5 Fitzgerald ePub titles                             │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ extract.py    ebooklib → cleaned chapter text                    │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ segment.py    chunking · author-style passage selection          │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ generate_instructions.py    teacher LLM → instruction/response   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ build_dataset.py            dataset.jsonl (3,762 examples)       │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ PEFT TRAIN   Transformers + PEFT · LoRA on Qwen2.5-3B            │',
      '│              fitzgerald_lora/ adapter (~479 MB)                  │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ loaded at runtime',
      '                                 ▼',
      '                       Bookgen `llm-service` (GPU)',
    ].join('\n'),
    inputs: [
      { label: 'Source books', format: 'ePub', description: '5 Fitzgerald titles.' },
    ],
    outputs: [
      { label: 'Adapter weights', format: '~479 MB', description: 'fitzgerald_lora/ for Bookgen llm-service.' },
      { label: 'Dataset', format: 'JSONL', description: '3,762 instruction pairs.' },
    ],
  },

  'getzoned-marketing': {
    summary:
      'Next.js 14 marketing site for the GetZoned app: server components for content, Framer Motion + R3F/Spline for the 3D hero and animation, App Router modals for early-access / host-event flows, and serverless API routes that push waitlist data into Google Sheets via Apps Script.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ VISITOR     Next.js 14 (App Router) · Framer Motion · R3F · Spline│',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ APP ROUTER   Early-access · host-event · choice flows (modals)   │',
      '└──┬───────────────────────────────────────────────────────┬───────┘',
      '   │ POST /api/register                                    │ POST /api/feedback',
      '   ▼                                                       ▼',
      '┌───────────────────────────────────┐         ┌──────────────────────┐',
      '│ Google Apps Script integration    │         │ Gmail (notification) │',
      '│ → Google Sheets waitlist          │         └──────────────────────┘',
      '└───────────────────────────────────┘',
      '',
      'BUILD   Static export `out/` · paired with getzoned.in product',
    ].join('\n'),
    inputs: [
      { label: 'Registration', format: 'Form JSON', description: 'Early access, host event, feedback flows.' },
    ],
    outputs: [
      { label: 'Waitlist rows', format: 'Google Sheets', description: 'Apps Script integration.' },
      { label: 'Static site', format: 'out/', description: 'Export build paired with getzoned.in app.' },
    ],
  },

  'football-analytics': {
    summary:
      'Football intelligence platform: feature store ingests match telemetry, medical history, and contract context; four ML modules (injury risk, valuation, performance, team) read from it; a decisions API surfaces alerts and projections to a clubs-facing dashboard.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SOURCES     GPS/load telemetry · medical EHR · scouting · league │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ ETL · validation',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ FEATURE STORE   per-player time series · contract context        │',
      '└──┬───────────────┬──────────────────┬──────────────┬─────────────┘',
      '   │               │                  │              │',
      '   ▼               ▼                  ▼              ▼',
      '┌──────────┐ ┌──────────────┐ ┌──────────────┐ ┌──────────────┐',
      '│ Injury   │ │ Valuation    │ │ Performance  │ │ Team /       │',
      '│ risk     │ │ projection   │ │ tracking     │ │ squad model  │',
      '│ model    │ │ (2–5 season) │ │ (drift)      │ │              │',
      '└─────┬────┘ └──────┬───────┘ └──────┬───────┘ └──────┬───────┘',
      '      └────────────┬┴───────────────┬┴────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DECISION API   risk scores · valuation bands · alerts · plans    │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DASHBOARD   Medical · performance · coaching · executive views   │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    layers: [
      { title: 'Sources', detail: 'GPS/load telemetry, medical history, contract context, scouting datasets, league feeds.' },
      { title: 'Feature store', detail: 'Per-player time series with contract metadata; serves all four ML modules from a single source of truth.' },
      { title: 'Injury intelligence', detail: 'Multi-signal model that flags risk before breakdown.' },
      { title: 'Valuation', detail: '2–5 season market value projections from career trajectories.' },
      { title: 'Performance', detail: 'Drift detection and load optimization tied to training-to-match alignment.' },
      { title: 'Team hub', detail: 'Medical, performance, athletic, and coaching views aligned on availability and decisions.' },
    ],
    inputs: [
      { label: 'Player telemetry', format: 'Time series', description: 'Load, minutes, GPS-style metrics.' },
      { label: 'Medical history', format: 'Structured events', description: 'Injuries and return-to-play windows.' },
    ],
    outputs: [
      { label: 'Risk scores', format: 'Dashboard %', description: 'Injury likelihood bands per player.' },
      { label: 'Valuation bands', format: 'EUR projections', description: 'Transfer and development decisions.' },
    ],
  },

  'yolo-sports-tracking': {
    summary:
      'Computer-vision pipeline: video frames are decoded into a queue, a YOLO detector locates players and ball per frame, a multi-object tracker maintains IDs across occlusions, and outputs (per-frame positions, IDs, derived stats) are exported for downstream analytics.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ INPUT       Match video · MP4 / RTSP stream                      │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 │ OpenCV decode',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ FRAME QUEUE  bounded buffer · GPU batching                       │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DETECTOR    YOLO (Ultralytics) · PyTorch · player + ball classes │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ TRACKER     ByteTrack / SORT · ID maintenance across occlusions  │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ ANALYTICS   speed · zones · heatmaps · possession proxies        │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ EXPORT      CSV/JSON track logs · annotated video                │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'Video frames', format: 'MP4 / stream', description: 'Broadcast or training footage.' },
    ],
    outputs: [
      { label: 'Track IDs', format: 'CSV / JSON', description: 'Per-frame player and ball positions.' },
      { label: 'Analytics', format: 'Derived stats', description: 'Speed, zones, possession proxies.' },
    ],
  },

  'web-scraper-evasion': {
    summary:
      'Resilient scraping stack: a crawl queue feeds a session/proxy pool, requests flow through a bypass layer (UA rotation, fingerprinting, verification handlers), and a parsing stage normalizes results before structured export.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ INPUT       Target URLs · crawl seeds                            │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CRAWL QUEUE   dedup · backoff · rate limits · failure recovery   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SESSION POOL  proxy rotation · UA + header rotation · cookies    │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ BYPASS LAYER  CAPTCHA / verification handlers · Selenium fallback│',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ PARSE         BeautifulSoup / structured extractors              │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ EXPORT        JSON / CSV · deduped records for NLP pipelines     │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'Target URLs', format: 'List / queue', description: 'Protected sites with rate limits.' },
    ],
    outputs: [
      { label: 'Structured records', format: 'JSON / CSV', description: 'Deduped crawl results for NLP pipelines.' },
    ],
  },

  'ai-cost-optimizer': {
    summary:
      'GenOps cost-audit platform: an infrastructure questionnaire produces a service inventory; collectors pull provider usage telemetry; an analyzer compares cost vs quality per model and emits a migration/throttle/cache playbook with quantified savings.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ DISCOVERY   Infra questionnaire · API keys · service map         │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ INVENTORY   Apps · envs · providers · models per endpoint        │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ COLLECTORS  OpenAI · Anthropic · OpenRouter usage telemetry      │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ TELEMETRY   token aggregation · $ estimate · per-task cost bands │',
      '│             PostgreSQL · Prometheus-style metrics                │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ ANALYZER    model compare (GPT-4o · mini · open weights · …)     │',
      '│             cost vs quality bands · routing recommendations      │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ PLAYBOOK    Markdown report · migrate · throttle · cache · batch │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'API inventory', format: 'Keys + service map', description: 'Apps, envs, providers per company.' },
      { label: 'Usage logs', format: 'Prompt/completion tokens', description: 'Per endpoint and model.' },
    ],
    outputs: [
      { label: 'Cost report', format: 'Dashboard + $ estimate', description: 'Spend by model and task type.' },
      { label: 'Playbook', format: 'Markdown', description: 'Migrate, throttle, cache recommendations.' },
    ],
  },

  'course-studio': {
    summary:
      'Course authoring pipeline: an LLM outlines a syllabus, a structured generator produces module/lesson/slide content, python-pptx renders branded decks with speaker notes, a TTS stage attaches per-slide narration, and an exporter bundles the artifacts for an LMS package.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ INPUT       Course brief · audience · objectives · constraints   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ OUTLINE     LLM (FastAPI service) · syllabus + objectives        │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CONTENT GEN  module → lesson → slide hierarchy + speaker notes   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SLIDE RENDER  python-pptx · branded templates · diagrams         │',
      '└──┬──────────────────────────────────────────────┬────────────────┘',
      '   │                                              │',
      '   ▼                                              ▼',
      '┌──────────────────────┐                ┌──────────────────────────┐',
      '│ TTS                  │                │ Markdown instructor guide│',
      '│ per-slide narration  │                │                          │',
      '└──────────┬───────────┘                └────────────┬─────────────┘',
      '           │                                         │',
      '           └──────────────────┬──────────────────────┘',
      '                              ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ EXPORT      LMS package · PPTX + MP3/WAV per slide + guide       │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    inputs: [
      { label: 'Course brief', format: 'Text', description: 'Audience, objectives, module count.' },
    ],
    outputs: [
      { label: 'Slide deck', format: 'PPTX', description: 'Layouts + speaker notes.' },
      { label: 'Audio', format: 'MP3/WAV', description: 'Per-slide narration.' },
    ],
  },

  'data-lineage': {
    summary:
      'End-to-end data-lineage platform: heterogeneous connectors pull SQL and DAG metadata from warehouses, a parser extracts column-level mappings, an access-verification stage gates exposure, and a graph loader publishes source → transform → target edges to a knowledge graph.',
    diagram: [
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SOURCES   Airflow DAGs · Snowflake · Oracle · BigQuery · .sql    │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CONNECTORS  metadata + raw query pull · per-source adapters      │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ SQL PARSER  SQLGlot / sqlparse → tables · columns · transforms   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ ACCESS CHECK   ownership · permissions · governance gates        │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ NORMALIZE     canonical schema · entity ids · transform metadata │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ GRAPH LOADER  Neo4j writer · source → transform → target edges   │',
      '└────────────────────────────────┬─────────────────────────────────┘',
      '                                 ▼',
      '┌──────────────────────────────────────────────────────────────────┐',
      '│ CONSUMERS   Lineage UI · impact analysis · audit / governance    │',
      '└──────────────────────────────────────────────────────────────────┘',
    ].join('\n'),
    layers: [
      { title: 'Connectors', detail: 'Per-source adapters for Airflow DAG metadata, Snowflake, Oracle, BigQuery, and raw SQL files — pull both queries and job metadata.' },
      { title: 'SQL parser', detail: 'SQLGlot/sqlparse extracts tables, columns, transforms, and write targets at column-level granularity.' },
      { title: 'Governance', detail: 'Access verification and ownership checks before any lineage edge is exposed to downstream consumers.' },
      { title: 'Normalization', detail: 'Canonical entity ids and transform metadata so heterogeneous sources stitch into one graph.' },
      { title: 'Graph', detail: 'Neo4j loader writes source → transform → target triples; supports column-level lineage and impact analysis queries.' },
    ],
    inputs: [
      { label: 'SQL artifacts', format: '.sql / warehouse API', description: 'Queries and job metadata from heterogeneous sources.' },
    ],
    outputs: [
      { label: 'Lineage graph', format: 'Neo4j edges', description: 'Impact analysis and column-level trace.' },
    ],
  },
}
