/**
 * Upload public/img-car/*.MOV to Cloudinary and patch lib/img-car-carousel.ts
 * Run: bun run upload:img-car-videos
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs'
import { resolve, basename } from 'node:path'
import { v2 as cloudinary } from 'cloudinary'

const ROOT = resolve(process.cwd())
const IMG_CAR_DIR = resolve(ROOT, 'public/img-car')
const OUT_FILE = resolve(ROOT, 'lib/img-car-carousel.ts')

function loadEnv() {
  const envPath = resolve(ROOT, '.env')
  const raw = readFileSync(envPath, 'utf8')
  for (const line of raw.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq)
    const value = trimmed.slice(eq + 1)
    if (!process.env[key]) process.env[key] = value
  }
}

loadEnv()

const cloudName = process.env.CLOUDINARY_CLOUD_NAME
const apiKey = process.env.CLOUDINARY_API_KEY
const apiSecret = process.env.CLOUDINARY_API_SECRET
const folder = `${process.env.CLOUDINARY_FOLDER ?? 'portfolio'}/img-car`

if (!cloudName || !apiKey || !apiSecret) {
  console.error('Missing CLOUDINARY_* in .env')
  process.exit(1)
}

cloudinary.config({
  cloud_name: cloudName,
  api_key: apiKey,
  api_secret: apiSecret,
  secure: true,
})

async function uploadFile(
  filePath: string,
  publicId: string,
): Promise<{ secure_url: string }> {
  const result = await cloudinary.uploader.upload(filePath, {
    resource_type: 'video',
    folder,
    public_id: publicId,
    overwrite: true,
    unique_filename: false,
  })
  return { secure_url: result.secure_url }
}

function slugFromFilename(name: string): string {
  return basename(name).replace(/\.[^.]+$/, '').toLowerCase()
}

async function main() {
  const files = readdirSync(IMG_CAR_DIR)
    .filter((f) => /\.(mov|mp4|webm)$/i.test(f))
    .sort()

  if (files.length === 0) {
    console.error(`No videos found in ${IMG_CAR_DIR}`)
    process.exit(1)
  }

  console.log(`Found ${files.length} videos in public/img-car/`)

  const cloudMap: Record<string, string> = {}

  for (let i = 0; i < files.length; i++) {
    const file = files[i]
    const id = slugFromFilename(file)
    const filePath = resolve(IMG_CAR_DIR, file)
    console.log(`[${i + 1}/${files.length}] Uploading ${file}…`)

    const result = await uploadFile(filePath, id)
    cloudMap[file] = result.secure_url
    console.log(`  → ${result.secure_url}`)
  }

  const fileListLiteral = files
    .map((f) => `  '${f}',`)
    .join('\n')

  const cloudLiteral = Object.entries(cloudMap)
    .map(([file, url]) => `  '${file}': '${url}',`)
    .join('\n')

  const content = `import type { LayeredItem } from '@/components/sections/LayeredVideoScroll'

/** Seven clips from \`public/img-car/\` — Cloudinary delivery (generated by upload:img-car-videos) */
const IMG_CAR_FILES = [
${fileListLiteral}
] as const

const LOCAL_SRC: Record<(typeof IMG_CAR_FILES)[number], string> = {
${files.map((f) => `  '${f}': '/img-car/${f}',`).join('\n')}
}

const CLOUDINARY_SRC: Record<(typeof IMG_CAR_FILES)[number], string> = {
${cloudLiteral}
}

export const IMG_CAR_CAROUSEL_ITEMS: LayeredItem[] = IMG_CAR_FILES.map(
  (file, index) => ({
    type: 'video' as const,
    src: CLOUDINARY_SRC[file],
    caption: \`Frame \${String(index + 1).padStart(2, '0')}\`,
  }),
)

/** @deprecated Use IMG_CAR_CAROUSEL_ITEMS */
export const ABOUT_CAROUSEL_ITEMS = IMG_CAR_CAROUSEL_ITEMS
`

  writeFileSync(OUT_FILE, content, 'utf8')
  console.log(`\nWrote ${OUT_FILE}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
